# Generated by Django 5.1.1 on 2024-09-12 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="user_image/"),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FE", "Front-end Developer"),
                            ("BE", "Back-end Developer"),
                            ("FS", "Fullstack Developer"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
